name: Scrape Price Data Regularly

on:
  schedule:
    - cron: '0 21 * * *' # 日本時間午前6時に変更 (UTCで前日21時)
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # ジョブ全体のタイムアウトを6時間弱に設定 (デフォルトは360分)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # ログに合わせて3.12を使用

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run scraper to update data for all brands
        run: python scraper.py
        # timeout-minutes: 330 # スクレイピング自体のタイムアウトも設定可能 (ジョブ全体のタイムアウトより短く)

      - name: Commit and push data changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git add brands.json || echo "brands.json not modified" # brands.jsonがない、または変更がない場合のエラーを抑制
          
          # 変更があるか確認
          if ! git diff --staged --quiet; then
            git commit -m "Automated data update by GitHub Actions $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No data changes to commit."
          fi